create_clock -name cpu_clk -period 10 -waveform {0 5} [get_ports clk]
set_clock_transition -rise 0.1 [get_clocks cpu_clk]
set_clock_transition -fall 0.1 [get_clocks cpu_clk]
set_clock_uncertainty 0.1 [get_clocks cpu_clk]
set_input_delay -max 1.0 -clock [get_clocks cpu_clk] [get_ports {input_pins[*]}]
set_output_delay -max 1.0 -clock [get_clocks cpu_clk] [get_ports {output_pins[*] halted}]
